# Generated by Django 3.2.3 on 2021-11-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hub', max_length=20)),
                ('listen_address', models.CharField(default='0.0.0.0', max_length=30)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
