# Generated by Django 3.2.3 on 2021-11-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_con', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hub',
            new_name='Control_Hub',
        ),
    ]
