# Generated by Django 3.2.3 on 2021-11-07 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20211107_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitobjectdetection',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 11, 27, 52, 985586, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 11, 27, 52, 983367, tzinfo=utc)),
        ),
    ]
