# Generated by Django 3.2.3 on 2021-11-07 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import units.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20211107_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitobjectdetection',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 12, 27, 58, 868478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 12, 27, 58, 866684, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='UnitFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=units.models.unit_folder)),
                ('caption', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 11, 7, 12, 27, 58, 867582, tzinfo=utc))),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='units.unit')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='UnitActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail', models.TextField(default='Unknown activity recorded')),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 11, 7, 12, 27, 58, 868104, tzinfo=utc))),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='units.unit')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
