# Generated by Django 3.2.3 on 2021-11-08 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_auto_20211107_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitactivity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 3, 33, 533215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitfile',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 3, 33, 532588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitobjectdetection',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 3, 33, 533854, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 3, 33, 531702, tzinfo=utc)),
        ),
    ]
