# Generated by Django 3.2.3 on 2021-11-08 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0012_auto_20211108_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitactivity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 9, 20, 698519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitfile',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 9, 20, 697966, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitobjectdetection',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 9, 20, 699025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 3, 9, 20, 697289, tzinfo=utc)),
        ),
    ]
