# Generated by Django 3.2.3 on 2021-11-16 23:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0015_auto_20211116_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 23, 7, 23, 983267, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='unitfile',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 23, 7, 23, 980310, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitobjectdetection',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 23, 7, 23, 982340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 23, 7, 23, 979085, tzinfo=utc)),
        ),
    ]
