# Generated by Django 3.2.3 on 2021-11-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedUsers',
            fields=[
                ('id', models.TextField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'authorised_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.TextField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('last_statrep', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
    ]
