# Generated by Django 3.2.3 on 2021-11-06 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import interface.models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorisedUser',
            fields=[
                ('id', models.TextField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
            ],
            options={
                'db_table': 'authorised_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.TextField(blank=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('last_statrep', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', stdimage.models.StdImageField(upload_to=interface.models.unit_folder)),
                ('caption', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 22, 3, 41, 707609, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_photos', to='interface.unit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='interface.unit')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.DeleteModel(
            name='AuthorisedUsers',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
