# Generated by Django 3.2.3 on 2021-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.TextField(blank=True, default=483965),
        ),
    ]
