# Generated by Django 3.2.3 on 2021-11-06 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20211106_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitphoto',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 22, 8, 35, 897093, tzinfo=utc)),
        ),
    ]
