# Generated by Django 3.2.3 on 2021-12-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetection',
            name='detected_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.TextField(blank=True, default=309304),
        ),
    ]
