# Generated by Django 3.2.3 on 2021-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20211202_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedetection',
            options={'ordering': ['-time']},
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.TextField(blank=True, default=239790),
        ),
    ]
